name: Generate 3D Contribution

on:
    schedule:
        - cron: "15 0 * * *"
    workflow_dispatch:

permissions:
    contents: write

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: yoshi389111/github-profile-3d-contrib@0.7.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  USERNAME: LeAnhTuanIT

            - uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: output
                  publish_dir: profile-3d-contrib
                  destination_dir: 3d-contrib
                  keep_files: true
